# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - id: "sonr"
    goos:
      - linux
      - darwin
    hooks:
      pre:
        - go mod tidy
    dir: "cmd/sonrd"
    binary: "sonr"
    tags: "cli"

  - id: "sonrd"
    dir: "cmd/sonrd"
    binary: "sonrd"
    hooks:
      post:
        - mkdir dist
        - cp -r release/v* dist/
    skip: true

  - id: "highwayd"
    dir: "cmd/sonrd"
    binary: "highwayd"
    tags: "highway"
    goos:
      - linux
      - darwin

  - id: "highway-dashboard"
    dir: "cmd/sonrd"
    binary: "highway-dashboard"
    tags: "dashboard"

    goos:
      - linux
      - darwin

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: sonr-io
    name: sonr

  draft: true
  discussion_category_name: Releases

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # What to do with the release notes in case there the release already exists.
  #
  # Valid options are:
  # - `keep-existing`: keep the existing notes
  # - `append`: append the current release notes to the existing notes
  # - `prepend`: prepend the current release notes to the existing notes
  # - `replace`: replace existing notes
  #
  # Default is `keep-existing`.
  mode: append

  # Header template for the release body.
  # Defaults to empty.
  header: |
    ## New Sonr Release ({{ .Date }})

    Introducing {{ .Tag }}, the latest {{.ProjectName}} release!

  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## ---
    ## Thanks for your support!
    ##
    ## [The Sonr Team](https://sonr.io)
    ## [Sonr Community](https://sonr-io.circle.so/join?invitation_token=5fe804d13bd4a11ddaa79447f4a99cdbad80b1bf-aa8cb322-f689-4002-8ad1-47aab39afefc)
    ## [Twitter](https://twitter.com/sonrprotocol)

  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: true
  extra_files:
    - glob: "./release/**.tar.gz"

brews:
  -
    tap:
      owner: sonr-io
      name: sonr
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: "Run `brew info sonr` for more information, or run `sonr --help`."
    homepage: "https://sonr.io"
    description: "The Official Sonr CLI tool for building and deploying services on the Sonr network/blockchain."
    license: "GPLv3"

# .goreleaser.yaml
nfpms:
  -
    package_name: sonr
    vendor: Sonr Inc.
    homepage: https://sonr.io/
    maintainer: The Sonr Team <team@sonr.io>
    description: The Official Sonr CLI tool for building and deploying services on the Sonr network/blockchain.
    license: GPLv3
    priority: extra
    meta: true
