# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy

universal_binaries:
- replace: true

builds:
  - id: "sonr-highway"
    dir: "node/highway"
    binary: "sonr-highway"
    main: "highway.go"
    goos:
      - windows
      - darwin

  - id: "sonr-cli"
    dir: "cmd/cli"
    main: "main.go"
    binary: "sonr-cli"
    goos:
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: i386
      - goos: linux
        goarch: arm
        goarm: armv7
      - goarm: mips64
        gomips: hardfloat

  - id: "sonrd"
    skip: true
    dir: "cmd/sonrd"
    binary: "sonrd"

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    tap:
      owner: sonr-io
      name: sonr
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: homebrew
    caveats: "Run `brew info sonr` for more information, or run `sonr --help`."
    homepage: "https://sonr.io"
    description: "The Official Sonr CLI tool for building and deploying services on the Sonr network/blockchain."
    license: "GPLv3"

# .goreleaser.yaml
nfpms:
  -
    package_name: sonr
    vendor: Sonr Inc.
    homepage: https://sonr.io/
    maintainer: The Sonr Team <team@sonr.io>
    description: The Official Sonr CLI tool for building and deploying services on the Sonr network/blockchain.
    license: GPLv3
    priority: extra
    meta: true

dockers:
  -
    id: docker-highway
    goos: linux
    goarch: amd64
    goarm: ''
    ids:
    - sonr-highway
    image_templates:
    - "sonr-io/highway:latest"
    - "gcr.io/sonr-io/highway:latest"
    dockerfile: './cmd/highway/Dockerfile'
    use: docker

    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.source https://github.com/sonr-io/sonr"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"

  -
    id: docker-sonrd
    goos: linux
    goarch: amd64
    goarm: ''
    ids:
    - sonr-cli
    image_templates:
    - "sonr-io/sonrd:latest"
    - "gcr.io/sonr-io/sonrd:latest"
    dockerfile: 'Dockerfile'
    use: docker

    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.source https://github.com/sonr-io/sonr"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"
