accounts:
  - name: alice
    coins: ["20000snr", "200000000stake"]
  - name: bob
    coins: ["10000snr", "100000000stake"]

build:
  binary: "sonrd"
  

faucet:
  name: bob
  coins: ["5snr", "100000stake"]

init:
  home: ".sonr"

validator:
  name: alice
  staked: "100000000stake"
