accounts:
  - name: alice
    coins: ["20000snr", "200000000stake"]
  - name: bob
    coins: ["10000snr", "100000000stake"]

build:
  binary: "sonrd"

client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"

faucet:
  name: bob
  coins: ["5snr", "100000stake"]

init:
  home: ".sonr"

host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":26657"
  api: ":1318"

validator:
  name: alice
  staked: "100000000stake"
