account: "0"
account_name: ""

accounts:
- coins:
  - 20000snr
  - 200000000stake
  name: alice
- coins:
  - 10000snr
  - 100000000stake
  name: bob

algo: secp256k1

build:
  binary: sonrd
cache_dir: /Users/pradn/Library/Caches
chain-id: sonr
coin-type: "118"
config_dir: /Users/pradn/Library/Application Support
device_id: 275C7EB7-F42F-5794-B278-D761673F2343
dry-run: false
faucet:
  coins:
  - 5snr
  - 100000stake
  name: bob
hd-path: ""
help: false
highway:
  address: ':'
  did: ""
  network: tcp
  port: 69420
home: .sonr
home_dir: /Users/pradn
index: "0"
init:
  home: .sonr
interactive: false
ipfs:
  path: ""
  port: 0
keyring-backend: test
keyring-dir: ""
ledger: false
libp2p:
  bootstrap:
    peers:
    - /dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
    - /dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
    - /dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
    - /dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt
    - /ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
    - /ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
  bootstrap_peers: []
  highwater: 400
  lowwater: 200
  rendevouz: /sonr/rendevouz/0.9.2
list-names: false
log_format: plain
log_level: info
multisig: []
multisig-threshold: 1
no-backup: false
nosort: false
output: json
overwrite: false
private_ip: ""
pubkey: ""
public_ip: ""
recover: false
trace: false
validator:
  name: alice
  staked: 100000000stake
wallet_dir: /Users/pradn/.sonr-wallet
