version: "3.8"

services:
  sonr.d:
    image: ghcr.io/sonr-io/sonrd:latest
    container_name: sonr-d0
    restart: unless-stopped
    depends_on:
      - sonr.hnsd
      - sonr.highway
    ports:
      - "127.0.0.1:24659:26659"
      - "127.0.0.1:24318:1318"
      - "127.0.0.1:24450:4500"

  sonr.highway:
    image: ghcr.io/sonr-io/highway:latest
    container_name: sonr-hw0
    restart: unless-stopped
    depends_on:
      - sonr.hnsd
    ports:
      - "127.0.0.1:22025:26225"
      - "127.0.0.1:22080:8080"
      - "127.0.0.1:22081:8081"

  sonr.hnsd:
    image: handshakeorg/hsd:latest
    container_name: sonr-hnsd0
    hostname: sonr_hnsd_host1
    volumes:
      - "./data/hnsd:/.sonr/data/hnsd"
    ports:
      - "127.0.0.1:27053:53/udp"
      - "27038:13038/udp"
