version: "3"

includes:
  docs:
    taskfile: ./docs/Taskfile.yaml
    dir: ./docs/static/openapi

  flutter:
    taskfile: ./flutter/Taskfile.yaml
    dir: ./flutter

  types:
    taskfile: ./proto/Taskfile.yaml
    dir: ./proto

  vue:
    taskfile: ./vue/Taskfile.yaml
    dir: ./vue

tasks:
  buf:
    cmds:
      - buf build
      - buf push

  build:
    cmds:
      - task: vue:build
      - goreleaser build --skip-validate --rm-dist

  serve:
    cmds:
      - starport chain serve

  release:
    cmds:
      - rm -rf dist
      - rm -rf release
      - goreleaser release
      - task: clean

  clean:
    cmds:
      - rm -rf dist
      - rm -rf release
      - go mod tidy
