version: '3'

includes:
  frontend:
    taskfile: ./cmd/dashboard/Taskfile.yaml
    dir: ./cmd/dashboard

tasks:
  export:
    cmds:
      - task: frontend:export

  build:
    cmds:
      - goreleaser build --skip-validate --rm-dist

  serve:
    cmds:
      - frontend:serve

  release:
    cmds:
      - rm -rf dist
      - rm -rf release
      - goreleaser release
      - rm -rf release
      - rm -rf dist

  clean:
    cmds:
      - rm -rf dist
      - rm -rf release
      - go mod tidy
      - frontend:clean

