version: '3'

includes:
  cli:
    taskfile: ./cmd/cli/Taskfile.yaml
    dir: ./cmd/cli
  motor:
    taskfile: ./cmd/motor/Taskfile.yaml
    dir: ./cmd/motor
  highway:
    taskfile: ./cmd/highway/Taskfile.yaml
    dir: ./cmd/highway
  frontend:
    taskfile: ./cmd/dashboard/Taskfile.yaml
    dir: ./cmd/dashboard

tasks:
  export:
    cmds:
      - task: frontend:export

  build:
    cmds:
      - goreleaser build --skip-validate --rm-dist

  serve:
    cmds:
      - task: highway:serve
      - task: frontend:serve

  release:
    cmds:
      - rm -rf dist
      - rm -rf release
      - goreleaser release
      - rm -rf release
      - rm -rf dist

  run:
    cmds:
      - task: cli:run


  clean:
    cmds:
      - rm -rf dist
      - rm -rf release
      - go mod tidy
      - frontend:clean

