version: '3'

includes:
  cli:
    taskfile: ./cmd/cli/Taskfile.yaml
    dir: ./cmd/cli
  motor:
    taskfile: ./cmd/motor/Taskfile.yaml
    dir: ./cmd/motor
  highway:
    taskfile: ./cmd/highway/Taskfile.yaml
    dir: ./cmd/highway
  dashboard:
    taskfile: ./cmd/dashboard/Taskfile.yaml
    dir: ./cmd/dashboard
  types:
    taskfile: ./proto/Taskfile.yaml
    dir: ./proto

tasks:
  export:
    cmds:
      - task: dashboard:export

  buf:
    cmds:
      - task: motor:buf
      - task: highway:buf
      - task: types:buf

  build:
    cmds:
      - goreleaser build --skip-validate --rm-dist

  serve:
    cmds:
      - task: highway:serve
      - task: dashboard:serve

  release:
    cmds:
      - rm -rf dist
      - rm -rf release
      - goreleaser release
      - task: clean

  clean:
    cmds:
      - rm -rf dist
      - rm -rf release
      - go mod tidy
      - task: dashboard:clean

