version: '3'

includes:
  frontend:
    taskfile: ./cmd/sonrd/frontend
    dir: ./cmd/sonrd/frontend/nextjs

tasks:
  export:
    cmds:
      - task: frontend:export

  build:
    cmds:
      - goreleaser build --skip-validate --rm-dist

  serve:
    cmds:
      - goreleaser serve --release

  release:
    cmds:
      - rm -rf dist
      - rm -rf release
      - goreleaser release
      - rm -rf release
      - rm -rf dist
