name: Notifier Workflow

on:
  workflow_run:
    workflows: ["Release Workflow"]
    types:
      - completed

jobs:
  status:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.status.outputs.result }}
    steps:
      - name: Determine Status
        id: status
        run: echo "::set-output name=result::${{ github.event.workflow_run.conclusion }}"
