name: Notifier Workflow

# Controls when the action will run.
on:
  workflow_run:
    workflows: ["Release Workflow"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Checks if Build has succeeded.
  # Returns: `needs.result.outputs.is_success == 'failure' |  `success``
  status:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.status.outputs.result }}
    steps:
      - name: Determine Status
        id: status
        run: echo "::set-output name=result::${{ github.event.workflow_run.conclusion }}"
